# Generated by Django 4.2.2 on 2024-02-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veg_App', '0005_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
