# Generated by Django 4.2.2 on 2024-02-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Veg_App', '0006_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instruction', models.TextField()),
                ('imagefile', models.ImageField(upload_to='recipe/')),
                ('ingredients', models.TextField()),
                ('time_took', models.IntegerField()),
                ('calory', models.IntegerField()),
                ('serving', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('L', 'Lunch'), ('D', 'Dinner'), ('Bev', 'Bevarages'), ('Brk', 'Breakfast')], max_length=100)),
                ('recipe_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veg_App.recipe')),
            ],
        ),
    ]
