# Generated by Django 4.2.2 on 2024-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veg_App', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
