# Generated by Django 4.2.2 on 2024-02-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veg_App', '0013_remove_category_recipe_foreign_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category_ref',
        ),
    ]
