# Generated by Django 4.2.2 on 2024-02-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veg_App', '0014_remove_recipe_category_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Veg_App.category'),
        ),
    ]
