# Generated by Django 4.2.2 on 2024-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veg_App', '0015_recipe_category_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Bevarages', 'Bevarages'), ('Breakfast', 'Breakfast')], max_length=100),
        ),
    ]
